/** @type {import('@remix-run/dev').AppConfig} */
module.exports = {
	serverBuildTarget: 'arc',
	server: './server.js',
	serverDependenciesToBundle: [
		/^rehype.*/,
		/^remark.*/,
		/^unified.*/,
		/^unist.*/,
		/^hast.*/,
		/^bail.*/,
		/^trough.*/,
		/^mdast.*/,
		/^micromark.*/,
		/^decode.*/,
		/^character.*/,
		/^property.*/,
		/^space.*/,
		/^comma.*/,
		/^react-markdown$/,
		/^vfile.*/,
		/^ccount*/,
		/^markdown-table*/,
		/^is-buffer*/,
		/^extend*/,
	],
	ignoredRouteFiles: ['**/.*'],
	// appDirectory: "app",
	// assetsBuildDirectory: "public/build",
	// serverBuildPath: "server/index.js",
	// publicPath: "/_static/build/",
};
